name: Apollo Check
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APOLLO_VCS_BRANCH: ${{ github.head_ref }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: apollographql-gh-actions/install-rover@v1
      - uses: apollographql-gh-actions/rover-subgraph-lint@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ secrets.APOLLO_GRAPH_REF }}
          name: github
          schema: ./github.graphql
      - uses: apollographql-gh-actions/rover-subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ secrets.APOLLO_GRAPH_REF }}
          name: github
          schema: ./github.graphql
