name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set \
            APOLLO_GRAPH_REF=${{ secrets.APOLLO_GRAPH_REF }} \
            APOLLO_KEY=${{ secrets.APOLLO_KEY }} \
            GITHUB_API_TOKEN=${{ secrets.GH_API_TOKEN }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
