name: Fly Review
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  review:
    runs-on: ubuntu-latest
    concurrency:
      group: pr-${{ github.event.number }}
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/fly-pr-review-apps@1.5.0
        id: deploy
        with:
          region: yyz
          name: ${{ github.event.repository.name }}-pr-${{ github.event.number }}
          secrets: |
            APOLLO_GRAPH_REF=${{ secrets.APOLLO_GRAPH_REF }}
            APOLLO_KEY=${{ secrets.APOLLO_KEY }}
            GITHUB_API_TOKEN=${{ secrets.GH_API_TOKEN }}
